# Generated by Django 5.1.6 on 2025-03-07 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organic', models.BooleanField(default=False)),
                ('pesticide_free', models.BooleanField(default=False)),
                ('water_usage', models.FloatField(blank=True, help_text='Water usage in liters', null=True)),
                ('soil_type', models.CharField(blank=True, max_length=100, null=True)),
                ('fertilizer_type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('certification', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('qr_code', models.CharField(max_length=100, unique=True)),
                ('carbon_footprint', models.FloatField(default=0.0)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api_app.producer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('FARM', 'Farming'), ('PROC', 'Processing'), ('PACK', 'Packaging'), ('DIST', 'Distribution'), ('RET', 'Retail')], max_length=4)),
                ('location', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='api_app.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Turf',
        ),
        migrations.AddField(
            model_name='farmingpractice',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farming_practice', to='api_app.product'),
        ),
    ]
