# Generated by Django 5.1.6 on 2025-03-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_remove_producer_user_remove_product_producer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmingtip',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farming_tips/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
