# Generated by Django 5.1.6 on 2025-03-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_farmingtip_image_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('FARMER', 'Farmer'), ('CONSUMER', 'Consumer')], default='CONSUMER', max_length=10),
        ),
    ]
