# Generated by Django 5.1.6 on 2025-05-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
